#' Parse a HP d300 *Print Map* XML report into a tidy tibble
#'
#' The XML generated by an HP / Tecan d300 digital dispenser contains a
#' worksheet named **“Tabular”**.  This helper reads that sheet, normalises
#' the table, and returns one row per well.
#'
#' @param file `character(1)`. Path to a `.xml` print‑map file.
#' @param add_prefix Either
#'   * a single **character** string that will be prepended to every
#'     *numeric‑only* `well.contents` entry (default `"BIO-"`), **or**
#'   * `FALSE` to leave numeric IDs unchanged.
#'   Any other value throws an error.
#'
#' @return A tibble with columns:
#' \describe{
#'   \item{plate}{Plate identifier extracted from the file.}
#'   \item{well}{Alphanumeric well ID (e.g. `"A01"`).}
#'   \item{compound}{Character code (see `add_prefix` behaviour).}
#'   \item{concentration}{Numeric single‑fluid concentration (0 when missing).}
#'   \item{dmso.percent}{Numeric DMSO content.}
#' }
#' @export
#'
#' @importFrom xml2 read_xml xml_ns xml_find_first xml_find_all xml_attr xml_text
#' @importFrom dplyr select mutate case_when rename
#' @importFrom stringr str_replace_all
#' @importFrom magrittr %>%
parse_printmap <- function(file, add_prefix = "BIO-") {

  ## ── Validate `add_prefix` ────────────────────────────────────────────────
  if (isFALSE(add_prefix)) {
    use_prefix <- FALSE
  } else if (is.character(add_prefix) && length(add_prefix) == 1L) {
    use_prefix <- TRUE
  } else {
    stop("`add_prefix` must be a single string or FALSE.", call. = FALSE)
  }

  ## ── 1. Locate the “Tabular” worksheet ───────────────────────────────────
  printmap <- xml2::read_xml(file)
  ns       <- xml2::xml_ns(printmap)

  tabular  <- xml2::xml_find_first(
    printmap, ".//ss:Worksheet[@ss:Name='Tabular']", ns)

  if (is.na(tabular))
    stop("Tabular worksheet not found in ", file, call. = FALSE)

  table_nd <- xml2::xml_find_first(tabular, ".//ss:Table", ns)
  if (is.na(table_nd))
    stop("Table node not found in Tabular worksheet of ", file, call. = FALSE)

  ## ── 2. Extract rows, honouring `ss:Index` ────────────────────────────────
  rows <- xml2::xml_find_all(table_nd, ".//ss:Row", ns)
  if (!length(rows))
    stop("No rows present in Tabular worksheet of ", file, call. = FALSE)

  extract_row <- function(row) {
    cells     <- xml2::xml_find_all(row, ".//ss:Cell", ns)
    out       <- character(0)
    col_index <- 1L

    for (cell in cells) {
      idx <- xml2::xml_attr(cell, "ss:Index", ns)
      if (!is.na(idx)) col_index <- as.integer(idx)

      val_nd <- xml2::xml_find_first(cell, ".//ss:Data", ns)
      val    <- if (!is.na(val_nd)) xml2::xml_text(val_nd) else NA_character_

      length(out) <- max(length(out), col_index)   # pad
      out[col_index] <- val
      col_index <- col_index + 1L
    }
    out
  }

  all_rows <- lapply(
    rows,
    extract_row
  )
  maxcols  <- max(lengths(all_rows))

  ## ── 3. Build data frame & clean headers ──────────────────────────────────
  raw_df <- do.call(
    rbind,
    lapply(all_rows, function(x) c(x, rep(NA_character_, maxcols - length(x))))
  ) %>%                           # <- magrittr pipe
    as.data.frame(stringsAsFactors = FALSE)

  names(raw_df) <- raw_df[1, ]
  raw_df        <- raw_df[-1, , drop = FALSE]

  names(raw_df) <- names(raw_df) %>%
    tolower() %>%
    stringr::str_replace_all("[ \n]", ".") %>%
    stringr::str_replace_all("%", "percent")

  ## ── 4. Normalise & coerce ────────────────────────────────────────────────
  dplyr::select(
    raw_df,
    plate, dispensed.well, well.contents,
    single.fluid.concentration, dmso.percent
  ) %>%
    dplyr::mutate(
      compound = dplyr::case_when(
        well.contents == "0" | is.na(well.contents)                    ~ "DMSO",
        grepl("^[0-9]+$", well.contents) & !use_prefix                 ~ well.contents,
        grepl("^[0-9]+$", well.contents) &  use_prefix                 ~ paste0(add_prefix, well.contents),
        TRUE                                                          ~ well.contents
      ),
      concentration = as.numeric(single.fluid.concentration)
    ) %>%
    dplyr::select(-single.fluid.concentration, -well.contents) %>%
    dplyr::mutate(
      concentration = dplyr::case_when(
        is.na(concentration) ~ 0,
        TRUE                 ~ signif(concentration, 4)
      ),
      dmso.percent  = signif(as.numeric(dmso.percent), 4)
    ) %>%
    dplyr::rename(well = dispensed.well)
}
